In [6]:
import time
import numpy as np
from scipy import spatial as spatial
import pandas as pd
import random
import math

In [17]:
# read dat file 
datContent = [i.strip().split() for i in open("../nsta24_sac.dat").readlines()]
# write it as a dataframe
df=pd.DataFrame(datContent,
                columns=["station name","lon","lat","?","?","?","agency","CSMT","?","?","?","?","?","?","date","?","?","?","?","?","?","?","?","?","?","?","?","?","?","?","?"]
               )
# filter CSMT
new_df=df[df["CSMT"]=="CSMT"]
new_df.to_csv('../existing_station.dat', sep=' ', header=None,index=None)
exist_lon=pd.to_numeric(new_df["lon"])
exist_lat=pd.to_numeric(new_df["lat"])
exist_lon_lat=np.array([exist_lon,exist_lat]).transpose()

In [19]:
#define the area of interest
lon_start = 120
lon_end = 122
lat_start= 21.8
lat_end= 25.5

step_count=0.025
step_lon= (lon_end-lon_start)/step_count
step_lat= (lat_end-lat_start)/step_count

#set of grid
#initialize grid storage
lon_storage=np.array([])
lat_storage=np.array([])

#compute individual points
for i in range(int(step_lon+2)):
    for j in range(int(step_lat+2)):
        lat_storage=np.append(lat_storage,lat_start+j*step_count)
        lon_storage=np.append(lon_storage,lon_start+i*step_count)

#add the two arrays together
grid_point_base= np.concatenate(([lon_storage],[lat_storage]))
#len(grid_point_base[0])
grid_point_base

array([[120.   , 120.   , 120.   , ..., 122.025, 122.025, 122.025],
       [ 21.8  ,  21.825,  21.85 , ...,  25.45 ,  25.475,  25.5  ]])

In [19]:
#merge exisiting stations in each grid
s=pd.DataFrame(exist_lon_lat,columns=["lon","lat"])
s1=pd.cut(s["lon"], np.arange(lon_start, lon_end, step_count))
s2=pd.cut(s["lat"], np.arange(lat_start, lat_end, step_count))
result=s.groupby([s1,s2]).mean()

lon_lat_nan=np.array([result["lon"],result["lat"]]).transpose()

#remove NaN
lon_lat_nan = lon_lat_nan[np.logical_not(np.isnan(lon_lat_nan))]
lon=np.array([])
lat=np.array([])

for i in range(len(lon_lat_nan)):
    if i%2==0:
        lon=np.append(lon,lon_lat_nan[i])
    else:
        lat=np.append(lat,lon_lat_nan[i])
lon_lat= np.concatenate(([lon],[lat])).transpose()


In [20]:
#define converter: lon lat to x y coords
def converter(lon2,lat2):
    lon1=lon_start
    lat1=lat_start
    dx = (lon2-lon1)*40000*math.cos((lat1+lat2)*math.pi/360)/360
    dy = (lat2-lat1)*40000/360
    return(np.array([dx,dy]))


In [21]:
#define the inputs
points=grid_point_base
combined_x_y_arrays=lon_lat
#transpose and list points
points_list = list(points.transpose())


In [22]:
#define kd tree function
def do_kdtree(combined_x_y_arrays,points):
    mytree = spatial.cKDTree(combined_x_y_arrays)
    dist, indexes = mytree.query(points)
    return dist, indexes


In [23]:
#initialize storages
storage=np.array([])
average_distance_storage=np.array([])

#run kd tree function
start = time.time()
iteration=1
for i in range(len(points_list)):
#for i in range(1000):
    storage=np.array([])
    combined_x_y_arrays=lon_lat
    points_list = list(points.transpose())
    for k in range(iteration):
        #do_kd_tree
        kd_result = do_kdtree(combined_x_y_arrays,points_list)
        result_compiler=pd.DataFrame(kd_result, index=["dist", "indexes"]).transpose()
        #store the nearest point
        #storage=np.append(storage, result_compiler["dist"][i])
        #convert lon/lat to the x/y
        lon_end,lat_end=combined_x_y_arrays[int(result_compiler["indexes"][i])]
        individual_x,individual_y=points_list[i]
        #calculate the distance
        dist=np.linalg.norm(converter(lon_end,lat_end)-converter(individual_x,individual_y))
        storage=np.append(storage, dist)
        #remove the nearest point
        combined_x_y_arrays=np.delete(combined_x_y_arrays, int(result_compiler["indexes"][i]),0)
    average_distance=np.array(sum(storage)/iteration)
    average_distance_storage=np.append(average_distance_storage,average_distance)
end = time.time()
print('Completed in: ',end-start)

Completed in:  10866.073817968369


In [24]:
#put the relevant data into dataframe
grid_value=pd.DataFrame(data=average_distance_storage.reshape(1,-1), index=["average_dist"])
cords=pd.DataFrame(data=points,index=["lon","lat"])
grid_value_and_cords=cords.append(grid_value)
grid_value_and_cords=grid_value_and_cords.transpose()

In [25]:
pd.set_option('display.max_rows', grid_value_and_cords.shape[0]+1)
grid_value_and_cords

lon     lat  average_dist
0      120.000  21.800     83.822217
1      120.000  21.825     85.206129
2      120.000  21.850     83.474381
3      120.000  21.875     81.056356
4      120.000  21.900     78.662096
5      120.000  21.925     76.293840
6      120.000  21.950     73.954086
7      120.000  21.975     71.645626
8      120.000  22.000     69.371584
9      120.000  22.025     67.135459
10     120.000  22.050     64.941166
11     120.000  22.075     62.793091
12     120.000  22.100     60.696142
13     120.000  22.125     58.655802
14     120.000  22.150     56.678186
15     120.000  22.175     55.694663
16     120.000  22.200     53.311169
17     120.000  22.225     50.967617
18     120.000  22.250     48.669779
19     120.000  22.275     46.424443
20     120.000  22.300     44.239603
21     120.000  22.325     42.124674
22     120.000  22.350     40.090721
23     120.000  22.375     38.150698
24     120.000  22.400     36.319661
25     120.000  22.425     34.614908
26     120.000  22.450     33.055983
27     120.000  22.475     31.664432
28     120.000  22.500     30.463202
29     120.000  22.525     29.475568
30     120.000  22.550     28.723574
31     120.000  22.575     28.226058
32     120.000  22.600     27.996591
33     120.000  22.625     28.041754
34     120.000  22.650     28.360235
35     120.000  22.675     27.761802
36     120.000  22.700     26.314369
37     120.000  22.725     25.091961
38     120.000  22.750     24.128802
39     120.000  22.775     23.456850
40     120.000  22.800     22.961358
41     120.000  22.825     21.641764
42     120.000  22.850     20.614073
43     120.000  22.875     19.923509
44     120.000  22.900     19.605725
45     120.000  22.925     19.018546
46     120.000  22.950     18.503580
47     120.000  22.975     16.487174
48     120.000  23.000     14.720851
49     120.000  23.025     13.304590
50     120.000  23.050     12.359322
51     120.000  23.075     11.996903
52     120.000  23.100     12.269092
53     120.000  23.125     13.136501
54     120.000  23.150     14.492646
55     120.000  23.175     16.215364
56     120.000  23.200     15.865164
57     120.000  23.225     14.868966
58     120.000  23.250     14.349249
59     120.000  23.275     14.357851
60     120.000  23.300     14.893854
61     120.000  23.325     15.904025
62     120.000  23.350     16.530076
63     120.000  23.375     17.118944
64     120.000  23.400     17.126306
65     120.000  23.425     16.234447
66     120.000  23.450     15.787219
67     120.000  23.475     15.822370
68     120.000  23.500     16.336786
69     120.000  23.525     17.287738
70     120.000  23.550     18.608420
71     120.000  23.575     18.601453
72     120.000  23.600     18.399590
73     120.000  23.625     18.614722
74     120.000  23.650     19.232861
75     120.000  23.675     20.217075
76     120.000  23.700     19.777857
77     120.000  23.725     19.933301
78     120.000  23.750     20.468059
79     120.000  23.775     21.353652
80     120.000  23.800     22.548782
81     120.000  23.825     24.007266
82     120.000  23.850     25.684278
83     120.000  23.875     27.539927
84     120.000  23.900     29.540567
85     120.000  23.925     31.658723
86     120.000  23.950     33.872356
87     120.000  23.975     36.163937
88     120.000  24.000     35.332058
89     120.000  24.025     35.625227
90     120.000  24.050     36.130200
91     120.000  24.075     36.838268
92     120.000  24.100     37.738002
93     120.000  24.125     38.816075
94     120.000  24.150     40.058090
95     120.000  24.175     41.449314
96     120.000  24.200     42.975258
97     120.000  24.225     44.622103
98     120.000  24.250     46.376971
99     120.000  24.275     48.228072
100    120.000  24.300     50.164753
101    120.000  24.325     52.177487
102    120.000  24.350     54.257809
103    120.000  24.375     56.398242
104    120.000  24.400     56.394292
105    120.000  24.425     56.689462
106    120.000  24.450     57.667555
107    120.000 

In [26]:
grid_value_and_cords.to_csv('../heatmap_real.txt', sep=' ', header=None,index=None)

In [28]:
list(points.transpose())

[array([120. ,  21.8]),
 array([120.   ,  21.825]),
 array([120.  ,  21.85]),
 array([120.   ,  21.875]),
 array([120. ,  21.9]),
 array([120.   ,  21.925]),
 array([120.  ,  21.95]),
 array([120.   ,  21.975]),
 array([120.,  22.]),
 array([120.   ,  22.025]),
 array([120.  ,  22.05]),
 array([120.   ,  22.075]),
 array([120. ,  22.1]),
 array([120.   ,  22.125]),
 array([120.  ,  22.15]),
 array([120.   ,  22.175]),
 array([120. ,  22.2]),
 array([120.   ,  22.225]),
 array([120.  ,  22.25]),
 array([120.   ,  22.275]),
 array([120. ,  22.3]),
 array([120.   ,  22.325]),
 array([120.  ,  22.35]),
 array([120.   ,  22.375]),
 array([120. ,  22.4]),
 array([120.   ,  22.425]),
 array([120.  ,  22.45]),
 array([120.   ,  22.475]),
 array([120. ,  22.5]),
 array([120.   ,  22.525]),
 array([120.  ,  22.55]),
 array([120.   ,  22.575]),
 array([120. ,  22.6]),
 array([120.   ,  22.625]),
 array([120.  ,  22.65]),
 array([120.   ,  22.675]),
 array([120. ,  22.7]),
 array([120.   ,  22.725

In [29]:
lon_lat

array([[120.1168 ,  23.0768 ],
       [120.1392 ,  23.2621 ],
       [120.1661 ,  23.0006 ],
       [120.1621 ,  23.2191 ],
       [120.1597 ,  23.3304 ],
       [120.1535 ,  23.4607 ],
       [120.1906 ,  22.90785],
       [120.1897 ,  22.9732 ],
       [120.1988 ,  23.1226 ],
       [120.1752 ,  23.2377 ],
       [120.1795 ,  23.5996 ],
       [120.193  ,  23.7025 ],
       [120.2242 ,  22.8143 ],
       [120.2172 ,  22.9188 ],
       [120.2115 ,  23.0089 ],
       [120.2482 ,  22.7834 ],
       [120.2407 ,  22.9813 ],
       [120.2458 ,  23.1234 ],
       [120.2441 ,  23.2926 ],
       [120.2396 ,  23.4835 ],
       [120.2491 ,  23.7046 ],
       [120.272  ,  22.6084 ],
       [120.2643 ,  22.7601 ],
       [120.2643 ,  22.8675 ],
       [120.2599 ,  23.1817 ],
       [120.2543 ,  23.751  ],
       [120.2874 ,  22.6229 ],
       [120.2926 ,  22.6905 ],
       [120.2889 ,  22.9648 ],
       [120.2957 ,  23.0791 ],
       [120.2769 ,  23.2137 ],
       [120.2992 ,  23.2977 ],
       [